name: Preview Deploy (Dev Branch)

on:
  push:
    branches:
      - dev

jobs:
  build-and-preview-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build site for preview
        run: |
          echo "VITE ENV BASE PATH=/photography-portfolio-dev/"
          BASE_PATH="/photography-portfolio-dev/" npm run build

      - name: Deploy to gh-pages-dev
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-dev
